### ISSUE TITLE
Retry logic for SQL Azure Throttling

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Data.SqlClient#84]
http://msdn.microsoft.com/en-us/library/azure/dn338079.aspx

http://channel9.msdn.com/Events/Microsoft-Azure/AzureConf-2014/Performance-Tuning-Microsoft-Azure-SQL-Database

**Comment by jorgef** [comment]
I am experiencing some "System.ComponentModel.Win32Exception: An existing connection was forcibly closed by the remote host" every now and then when using SQL Azure.

It would be great to have some configurable retry logic, otherwise I will need to add the retries at the application level.

Do you see this happening any time soon? Any recommendation of how to handle it in a centralized way?

Thanks

**Comment by dmitry-a-morozov** [comment]
Do you think this is high-priority issue ?
I work a lot with SQL Azure these days. Throttling is rare but possible.

For now you can try introduce re-try logic up in the stack  
```F#
type Get42 = SqlCommandProvider<"SELECT 42", @"Server=tcp:mhknbn2kdz.database.windows.net,1433;Database=AdventureWorks2012;User ID=sqlfamily;Password= sqlf@m1ly;Trusted_Connection=False;Encrypt=True;Connection Timeout=30", SingleRow = true>
let retryOnAzure() = 
    let rec loop n = 
        try 
            use cmd = new Get42()
            cmd.Execute() 
        with ex when true -> //put check here to make sure you deal with SQL Azure Throttling: https://msdn.microsoft.com/en-us/library/azure/dn338079.aspx 
            if n - 1 > 0 
            then 
                loop (n - 1)
            else
                reraise()
    loop 3
```

**Comment by jorgef** [comment]
I don't think it is high-priority but in my case it is not that rare. I already had 5 errors during the first week in production. So it may be important for others too (I guess it can be different on each Azure region).

Thanks for the retry logic code, the main issue is that I need to find a way to centralize that code, otherwise I will need to repeat it all over the place. And I found a bit challenging generalising code that uses the type provider, but I think it is achievable though.

Thanks again

**Comment by dmitry-a-morozov** [comment]
@jorgef Can you try to play with "ConnectRetryCount" and "ConnectRetryInterval" settings in connection string? I don't expect it to be helpful but give it a shot.
https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring%28v=vs.110%29.aspx
there is also a white paper
https://msdn.microsoft.com/en-us/library/dn632678.aspx

**Comment by jorgef** [comment]
I will give it a try, thanks!

**Comment by dmitry-a-morozov** [comment]
@jorgef Did it work for you?

**Comment by jorgef** [comment]
I am in process of testing it. I haven't deployed it to prod yet. 
I am planning to run a quick load test in a few days.
Will keep you updated.

**Comment by jorgef** [comment]
@dmitry-a-morozov Even with "ConnectRetryCount=10" we are still receiving connection errors every now and then (as ConnectRetryInterval's default is 1 sec, I didn't set that one).

Here you have an example from yesterday:

```
System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.) ---> System.ComponentModel.Win32Exception (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at <StartupCode$FSharp-Data-SqlClient>.$SqlCommand.ExecuteSeq@194.Invoke(Tuple`3 tupledArg)
   at <StartupCode$FSharp-Data-SqlClient>.$SqlCommand.-ctor@106-19.Invoke(Tuple`3 x)
```

**Comment by dmitry-a-morozov** [comment]
ok. I'll keep it in mind.
Give me some time to think of a good solution.

**Comment by jorgef** [comment]
Thanks

**Comment by dmitry-a-morozov** [comment]
I think I'm ready to address this issue and add support for generic retry functionality.
As it's been mentioned above it's not trivial to centralize/generalize re-try logic for sql command  types generated by the type provider. This is mostly due to the fact that Execute/AsyncExecute type signatures are unique per command type (as oppose to raw ADO.NET SqlCommand). 

One way to do it is :
```F#
val retry : times:int -> execute:(unit -> 'a) -> 'a

let result = retry 3 <| cmd.Execute(...)
```

But this code is not pretty and has high noise/signal ratio 

I propose following:
Constructor of generated command type will accept callback of type:
```F#
type Error = (SqlException -> bool)
```

If it returns true it means command will be re-executed. The type provider logic will take care of re-establishing connection to database if required (case of SQL Azure transitive needs exactly that)

If course this design opens possibility of creating creating infinite loops.

feedback is welcomed.

**Comment by jorgef** [comment]
Hi Dmitry, 

Could you please provide a usage example for the constructor alternative? 

Thanks

Jorge

**Comment by dmitry-a-morozov** [comment]
Hi Jorge,
It took me some time to put experimental branch together.
Here is unit tests that also can serve as a sample.
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/Retry/src/SqlClient.Tests/Retry.Tests.fs

Basic idea that you pass in ```error``` callback into command constructor. The callback type signature ```SqlException -> bool```. If it returns ```true``` command will be re-executed. In case of connection needs to be restored (connection.State <> ConnectionState.Open) it is callback responsibility to do it if connection external to command instance (passed into ctor). For internally managed connections it will done by provider logic. 

While working on this feature I realized how hard it to get right. 
So maybe it can wait. 

Let me know what you think.

P.S. 
![image](https://cloud.githubusercontent.com/assets/3004037/10625665/992b3a48-775a-11e5-87f8-8126fca1d9ca.png)

**Comment by dmitry-a-morozov** [comment]
@jorgef Seems like there is better support to address the issue starting .NET 4.6.1 (see "Improve connection open resiliency when connecting to Azure SQL Database")
http://blogs.msdn.com/b/dotnet/archive/2015/11/30/net-framework-4-6-1-is-now-available.aspx
